name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/Personal_Finance_Tracker
            git pull origin main
            
            # Update Backend
            cd backend
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi
            
            # Update Frontend (assuming Node is on EC2)
            cd ..
            npm install
            npm run build
            sudo cp -r dist/* /var/www/html/
            sudo systemctl restart nginx
